from datetime import datetime
from os import path
from typing import Optional

import numpy as np
import xarray as xr


def query_forecast(
    root_dir: str,
    date_hour: datetime,
    lead_time: int,
    variable_name: str,
    level: Optional[int] = None
) -> xr.DataArray:
    """
    Query forecast generated by the model.

    Args:
        root_dir (str): Root directory of the forecast data.
        date_hour (datetime): Date and hour of the forecast.
        lead_time (int): Lead time of the forecast.
        variable_name (str): Variable of interest.
        level (Optional[int], optional): Pressure level of the variable, only applicable for upper-air variables. Defaults to None.
    """

    dt_dir = date_hour.strftime(r"%Y/%Y%m/%Y%m%d")
    full_path = path.join(root_dir, dt_dir, date_hour.strftime(r"%Y%m%dT%H.nc"))

    ds = xr.open_dataset(full_path)
    lt = np.timedelta64(lead_time, "h")
    if level is None:
        return ds[variable_name].sel(time=date_hour, lead_time=lt).transpose("latitude", "longitude")
    else:
        return ds[variable_name].sel(time=date_hour, lead_time=lt, level=level).transpose("latitude", "longitude")


def query_complete_forecast(
    root_dir: str,
    date_hour: datetime,
    lead_time: int,
    surface_vars: list[str],
    upper_vars: list[str],
    pressure_levels: list[int],
) -> tuple[np.ndarray, np.ndarray]:
    """
    Query the complete forecast, with the same shape as the original dataset.

    Args:
        root_dir (str): Root directory of the forecast data.
        date_hour (datetime): Date and hour of the forecast.
        lead_time (int): Lead time of the forecast.
        surface_vars (list[str]): Surface variables.
        upper_vars (list[str]): Upper-air variables.
        pressure_levels (list[int]): Pressure levels of the upper-air variables.

    Returns:
        tuple[np.ndarray, np.ndarray]: Upper-air and surface variables.
    """

    surface_arr = []
    for var in surface_vars:
        surface_arr.append(query_forecast(root_dir, date_hour, lead_time, var))
    surface_x = np.stack(surface_arr, axis=-1)

    upper_arr = []
    for var in upper_vars:
        var_arr = []
        for lev in pressure_levels:
            var_arr.append(query_forecast(root_dir, date_hour, lead_time, var, lev))
        upper_arr.append(np.stack(var_arr, axis=0))
    upper_x = np.stack(upper_arr, axis=-1)

    return upper_x, surface_x
